import type { Metadata } from "next";
import { Roboto, Playfair_Display, Hina_Mincho } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const playFair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const hina = Hina_Mincho({
  weight: ["400"],
  variable: "--font-hina-mincho",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col ${roboto.className} ${playFair.variable} ${hina.variable} ${roboto.variable} font-light antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
